version: '3.8'
services:
  revobank:
    build: .
    container_name: revobank_app
    ports:
      - '5000:5000'
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/revobank
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: revobank_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: revobank
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
