"""change transaction_id to UUID

Revision ID: 9f6950e6b5a7
Revises: b6532d42693c
Create Date: 2025-04-07 16:05:44.975521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f6950e6b5a7'
down_revision: Union[str, None] = 'b6532d42693c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_transaction_id', table_name='transactions')
    op.create_unique_constraint(None, 'transactions', ['transaction_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.create_index('ix_transactions_transaction_id', 'transactions', ['transaction_id'], unique=False)
    # ### end Alembic commands ###
