"""Update transactions table

Revision ID: fe7a3712c786
Revises: 25d7e87079fa
Create Date: 2025-04-07 15:29:40.587002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe7a3712c786'
down_revision: Union[str, None] = '25d7e87079fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'accounts', ['account_number'])
    op.add_column('transactions', sa.Column('is_transfer', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('transfer_type', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('transactions', 'transfer_type')
    op.drop_column('transactions', 'is_transfer')
    op.drop_constraint(None, 'accounts', type_='unique')
    # ### end Alembic commands ###
